config/routes.rb
Rails.application.routes.draw do
  resources :bikes
  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
end

app/models/car.rb
class Car < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: [:show, :edit, :update, :destroy]

  # GET /bikes
  # GET /bikes.json
  def index
    @bikes = Bike.all
  end

  # GET /bikes/1
  # GET /bikes/1.json
  def show
  end

  # GET /bikes/new
  def new
    @bike = Bike.new
  end

  # GET /bikes/1/edit
  def edit
  end

  # POST /bikes
  # POST /bikes.json
  def create
    @bike = Bike.new(bike_params)

    respond_to do |format|
      if @bike.save
        format.html { redirect_to @bike, notice: 'Bike was successfully created.' }
        format.json { render :show, status: :created, location: @bike }
      else
        format.html { render :new }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bikes/1
  # PATCH/PUT /bikes/1.json
  def update
    respond_to do |format|
      if @bike.update(bike_params)
        format.html { redirect_to @bike, notice: 'Bike was successfully updated.' }
        format.json { render :show, status: :ok, location: @bike }
      else
        format.html { render :edit }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bikes/1
  # DELETE /bikes/1.json
  def destroy
    @bike.destroy
    respond_to do |format|
      format.html { redirect_to bikes_url, notice: 'Bike was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bike
      @bike = Bike.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bike_params
      params.require(:bike).permit(:name, :year, :value)
    end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
    respond_to :html, :json
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:name, :plate, :year, :value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/bikes/_form.html.erb
<%= form_with(model: bike, local: true) do |form| %>
  <% if bike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bike.errors.count, "error") %> prohibited this bike from being saved:</h2>

      <ul>
      <% bike.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :bike_name %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :bike_year %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, id: :bike_value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bikes/edit.html.erb
<h1>Editing Bike</h1>

<%= render 'form', bike: @bike %>

<%= link_to 'Show', @bike %> |
<%= link_to 'Back', bikes_path %>

app/views/bikes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bikes (mit best_in_place)</h1>

<table id='bikes' class='display'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th>Value</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bikes.each do |bike| %>
      <tr>
        <td><%= bike.name %></td>
        <td><%= bike.year %></td>
        <td><%= bike.value %></td>
        <td><%= link_to 'Show', bike %></td>
        <td><%= link_to 'Edit', edit_bike_path(bike) %></td>
        <td><%= link_to 'Destroy', bike, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bike', new_bike_path %>

app/views/bikes/new.html.erb
<h1>New Bike</h1>

<%= render 'form', bike: @bike %>

<%= link_to 'Back', bikes_path %>

app/views/bikes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= best_in_place @bike, :name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @bike.year %>
</p>

<p>
  <strong>Value:</strong>
  <%= @bike.value %>
</p>

<%= link_to 'Edit', edit_bike_path(@bike) %> |
<%= link_to 'Back', bikes_path %>

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :car_name %>
  </div>

  <div class="field">
    <%= form.label :plate %>
    <%= form.text_field :plate, id: :car_plate %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :car_year %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, id: :car_value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table id='cars' class='display'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Plate</th>
      <th>Year</th>
      <th>Value</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.name %></td>
        <td><%= car.plate %></td>
        <td><%= car.year %></td>
        <td><%= car.value %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @car.name %>
</p>

<p>
  <strong>Plate:</strong>
  <%= @car.plate %>
</p>

<p>
  <strong>Year:</strong>
  <%= @car.year %>
</p>

<p>
  <strong>Value:</strong>
  <%= @car.value %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestDataTables</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>